### ISSUE TITLE
AOT build fails

### ISSUE THREAD

**Issue by SAnDAnGE** [Romanchuk/angular-i18next-demo#1]
After running `npm install` I got the following when trying to build the AOT version:

```
C:\www\angular-i18next-demo [master ≡ +0 ~1 -0 !]
λ  npm run build:aot

> angular2-webpack-starter@5.1.1 build:aot C:\www\angular-i18next-demo
> ngc -p tsconfig-aot.json

Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'I18NextModule' was called.
```
I have the same problem using your library in an angular-cli project.

**Comment by MTRNord** [comment]
Making a wrapper file looking like this:

```
import {I18NextModule} from "angular-i18next";
import {NgModule} from "@angular/core";

@NgModule({
})
export class i18nextModule {
  constructor() {
    I18NextModule.forRoot();
  }
}
```
and using that as imports instead of direct usage did the trick for me I think

**Comment by Romanchuk** [comment]
@SAnDAnGE Thank you, i've reproduced it. Going to fix ASAP.

**Comment by SAnDAnGE** [comment]
@Romanchuk any feedback on a possible solution ?

**Comment by Romanchuk** [comment]
@SAnDAnGE After research i found same problems:
https://stackoverflow.com/questions/47686638/featuremodule-fails-during-an-aot-build-when-static-forroot-has-arguments
https://stackoverflow.com/questions/48225993/angular-call-function-in-forroot-method
To make it work I need to simplyfy forRoot method of I18NextModule. This means i need to remove all  function calls in method.
The new version of angular-i18next is upcomming in this week (also i would update demo).

**Comment by Romanchuk** [comment]
angular-i18next v3.2.0 released.
Demo updated. Aot build now completes succesfully.
There is one problem left in demo, it doesn't output to dist folder.

**Comment by SAnDAnGE** [comment]
@Romanchuk Issue fixed, thank you!
