### ISSUE TITLE
document.location.reload () to render new translation?

### ISSUE THREAD

**Issue by WebStew** [Romanchuk/angular-i18next-demo#2]
Hi,

More of a question really than an issue but in `/src/app/structure/header-controls/header.language.component.ts ` there is a call to `document.location.reload ()` do we really need to reload the entire application to get the view to re-render the translation change?

Currently on the application I am building when a user changes language the current view is not re-rendered. However if they then navigate off to another page ( without a refresh ) the correct translation is rendered on the new page.

I've used i18next in the past with React and when hooked up to the store the views just automatically re-render. Apologies I'm pretty new to angular.

**Comment by Romanchuk** [comment]
@WebStew  Short answer to you question: you don't have to call location.reload(), but i would  recommend to reload page =)

> However if they then navigate off to another page ( without a refresh ) the correct translation is rendered on the new page.

You found a bug: top navigation have been always refreshed page (without use of angular router navigation mechanism). Fixed now =)

Now navigation would not make you see correct language in a top bar, only in components inside <router-outlet>.

 i18next is a pure pipe that means that it will not rerender until input params would change (key or options), the correct language will render only for new pipe instances.
As i know in react you can call redraw of whole application, in angular you don't have this option. The only way to do it are through hacks: [check it out](https://stackoverflow.com/a/41873038/2208167)


The main reason why i prefer to reload page on locale change is that some UI components in your application could not change their format at runtime (date/datetime pickers or moment locale). You just set its locale on an application startup and do not trying to make 3rd party component dynamicaly configurable.
Or you could have use some other pure pipes that doesn't know anything about i18locale change.
Another problem is that you can't change LOCALE_ID dynamicaly (once it was resovled), this token could be used for localize angular controls and stuff...

And finally page reload can be positive for app performance. It would clean all memory after refresh =)

You must be wondering why is that i18next is not impure pipe than? Here is the answer:
https://github.com/Romanchuk/angular-i18next/pull/11#issuecomment-364725022

**Comment by WebStew** [comment]
Many thanks for the response @Romanchuk. I appreciate the links to the history on your decisions as well. I'll do some more reading around the pipes and revert. 

I suppose my biggest concern with a full page refresh is that I would lose my entire application state if it was saved somewhere. Is this a common problem and are there any recommendations to this?

**Comment by Romanchuk** [comment]
@WebStew
Depends of your project use cases.
Mostly user wants to change language before moving forward.
Use i18next language auto detect to set user preferred language.

Anyway i recommend to use router for main sections of the site, it would help to return back after user manual refresh (F5) and also could be helpfull for analytics and metrics (GA, yandex, application insights). If you have lists with filters, you might want to users share links that contain filter params.

Options for lang change:
- Show confirmation dialog before change language
- Show lang choose right after app init
- If user lang stores in db you can move language change functionality to some sort of setting. Without afraid of losing state.
- Just reload if your system is read only (or has just a few small forms)
- If your system is not tolerant to refresh at all. Than use one of the hacks to redraw whole application

**Comment by WebStew** [comment]
Okay thanks @Romanchuk. I definitely agree. User will probably only change language at the beginning and possible only ever once as well. Thanks so much for the time you spent replying and the information provided. Very much appreciated.
